name: Build And Push on Master
run-name: ${{ gitea.actor }} is runs ci pipeline
on: [push]

jobs:
  publish:
    runs-on: cth-ubuntu-latest
    if: gitea.ref == 'refs/heads/master'
    steps:
      - uses: https://github.com/actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install poetry
        run: pipx install poetry && pipx ensurepath
      - run: poetry export > docker_requirements.txt
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."git.oripoto.pw"]
              http = true
              insecure = true
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: git.oripoto.pw
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.PACKAGE_PUSH_TOKEN }}
      - name: Build and push Docker image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "git.oripoto.pw/cargsl/domovoy:${{gitea.sha}},git.oripoto.pw/cargsl/domovoy:latest"
